### ISSUE TITLE
Issue #134

### ISSUE THREAD

**Issue by zackmal** [learningshitinoakland/learningshitinoakland.github.io#2]
My issue is that I don't know what issues are.

**Comment by mattmaiorana** [comment]
This is crazy. I don't understand what's going on.

**Comment by DigitalCharlie** [comment]
We can assign someone to an issue! On the right!

**Comment by DigitalCharlie** [comment]
Can I tag someone? @mattmaiorana

**Comment by zackmal** [comment]
This issue is a sham! @mattmaiorana @DigitalCharlie @jaycarmona

**Comment by jaycarmona** [comment]
We've all got issues.

**Comment by DigitalCharlie** [comment]
Only one person can be assigned at a time

**Comment by zackmal** [comment]
**bold!**

**Comment by DigitalCharlie** [comment]
_STOP IT_

**Comment by DigitalCharlie** [comment]
**BOLD**

**Comment by DigitalCharlie** [comment]
**_STOP THIS MADNESS**_

**Comment by mattmaiorana** [comment]
<em>ITALICS</em>

**Comment by DigitalCharlie** [comment]
_this one?_
